apiVersion: v1
kind: Pod
metadata:
  name: marga-app
spec:
  containers:
  - name: marga-app
    image: mrmarga/jamuntekapp:v1
    env:
      - name: MYSQL_HOST
        value: "10.110.68.67"          # this is your mysql's service clusture IP, Make sure to change it with yours
      - name: MYSQL_PASSWORD
        value: "admin"
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_DB
        value: "mydb"
    ports:
      - containerPort: 5000
    imagePullPolicy: Always
    
