apiVersion: v1
kind: Service
metadata:
  name: marga-app-service
spec:
  selector:
    app: marga-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30009
  type: NodePort
