apiVersion: apps/v1
kind: Deployment
metadata:
  name: marga-app
  labels:
    app: marga-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marga-app
  template:
    metadata:
      labels:
        app: marga-app
    spec:
      containers:
        - name: marga-app
          image: mrmarga/jamuntekapp:v1
          env:
            - name: MYSQL_HOST
              value: "10.110.68.67"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
